cake-contrib/Cake.Issues.MsBuild

src/Cake.Issues.MsBuild.Tests/Cake.Issues.MsBuild.Tests.csproj
src/Cake.Issues.MsBuild.Tests/packages.config
src/Cake.Issues.MsBuild/Cake.Issues.MsBuild.csproj
src/Cake.Issues.MsBuild/MsBuildIssuesAliases.cs
src/Cake.Issues.MsBuild/packages.config

Add MsBuildIssuesProviderTypeName alias
Fixes #3

(GH-3) Add MsBuildIssuesProviderTypeName alias

---

cake.config
setup.cake
tools/packages.config

Update to Cake 0.23.0 for compatibility with latest Cake.Recipe
Fixes #11

(GH-11) Update to Cake 0.23.0

---

src/Cake.Issues.MsBuild.Tests/Cake.Issues.MsBuild.Tests.csproj
src/Cake.Issues.MsBuild/Cake.Issues.MsBuild.csproj

Update to Cake.Issues 0.2.0-beta0002
Fixes #13

(GH-13) Update to Cake.Issues 0.2.0-beta0002

---

src/Cake.Issues.MsBuild.Tests/Properties/AssemblyInfo.cs
src/Cake.Issues.MsBuild/Properties/AssemblyInfo.cs

Fix warnings

---

setup.cake

Fix version due to https://github.com/cake-contrib/Cake.Recipe/issues/200

Pin Cake.Recipe version

---

setup.cake

Use latest version of Cake.Recipe

Use latest version of Cake.Recipe

---

src/Cake.Issues.MsBuild.Tests/Cake.Issues.MsBuild.Tests.csproj
src/Cake.Issues.MsBuild.Tests/XmlFileLoggerFormatTests.cs
src/Cake.Issues.MsBuild/Cake.Issues.MsBuild.csproj
src/Cake.Issues.MsBuild/ILogFileFormat.cs
src/Cake.Issues.MsBuild/LogFileFormat.cs
src/Cake.Issues.MsBuild/MsBuildIssuesProvider.cs
src/Cake.Issues.MsBuild/XmlFileLoggerFormat.cs

Update to Cake.Issues 0.3.0
Fixes #22

(GH-22) Update to Cake.Issues 0.3.0

---

src/Cake.Issues.MsBuild/MsBuildIssuesAliases.cs

Add example for custom issue filter

Fix file name in example

---

src/Cake.Issues.MsBuild.Tests/Cake.Issues.MsBuild.Tests.csproj
src/Cake.Issues.MsBuild.Tests/Testfiles/FullLog.xml
src/Cake.Issues.MsBuild.Tests/XmlFileLoggerFormatTests.cs
src/Cake.Issues.MsBuild/XmlFileLoggerFormat.cs

(GH-10) Return project

---

tools/packages.config

Build with Cake 0.29.0
Fixes #30

(GH-30) Build with Cake 0.29.0

---

src/Cake.Issues.MsBuild.Tests/Cake.Issues.MsBuild.Tests.csproj
src/Cake.Issues.MsBuild.Tests/XmlFileLoggerFormatTests.cs
src/Cake.Issues.MsBuild/Cake.Issues.MsBuild.csproj
src/Cake.Issues.MsBuild/XmlFileLoggerFormat.cs

Update to Cake.Issues 0.4.0
Fixes #32

(GH-32) Update to Cake.Issues 0.4.0

---

src/Cake.Issues.MsBuild/MsBuildIssuesSettings.cs

Fix comment

---

src/Cake.Issues.MsBuild.Tests/Cake.Issues.MsBuild.Tests.csproj
src/Cake.Issues.MsBuild.Tests/MsBuildIssuesProviderFixture.cs
src/Cake.Issues.MsBuild.Tests/MsBuildIssuesProviderTests.cs
src/Cake.Issues.MsBuild/BaseMsBuildLogFileFormat.cs
src/Cake.Issues.MsBuild/Cake.Issues.MsBuild.csproj
src/Cake.Issues.MsBuild/MsBuildIssuesAliases.IssueProvider.cs
src/Cake.Issues.MsBuild/MsBuildIssuesAliases.XmlFileLoggerFormat.cs
src/Cake.Issues.MsBuild/MsBuildIssuesProvider.cs
src/Cake.Issues.MsBuild/MsBuildIssuesSettings.cs
src/Cake.Issues.MsBuild/XmlFileLoggerFormat.cs

Update to Cake.Issues 0.5.0
Fixes #41

Update to Cake.Issues 0.5.0

---

src/Cake.Issues.MsBuild.Tests/MsBuildIssuesProviderTests.cs
src/Cake.Issues.MsBuild.Tests/MsBuildIssuesSettingsTests.cs

Improve test cases

---

src/Cake.Issues.MsBuild.Tests/Cake.Issues.MsBuild.Tests.csproj
src/Cake.Issues.MsBuild.Tests/MsBuildIssuesProviderTests.cs
src/Cake.Issues.MsBuild.Tests/MsBuildIssuesSettingsTests.cs
src/Cake.Issues.MsBuild/Cake.Issues.MsBuild.csproj
src/Cake.Issues.MsBuild/LogFileFormat/XmlFileLoggerLogFileFormat.cs
src/Cake.Issues.MsBuild/MsBuildIssuesAliases.IssueProvider.cs

Update to Cake.Issues 0.5.0-beta0002

Update to Cake.Issues 0.5.0-beta0002

---

src/Cake.Issues.MsBuild.Tests/MsBuildIssuesSettingsTests.cs

Add more tests for MsBuildIssuesSettings

Add more tests for MsBuildIssuesSettings

---

src/Cake.Issues.MsBuild.Tests/Cake.Issues.MsBuild.Tests.csproj
src/Cake.Issues.MsBuild/Cake.Issues.MsBuild.csproj

Update Cake.Issues to 0.6.0 Beta 1
Fixes #48

(GH-48) Update Cake.Issues to 0.6.0 Beta 1

---

src/Cake.Issues.MsBuild.Tests/Cake.Issues.MsBuild.Tests.csproj
src/Cake.Issues.MsBuild.Tests/LogFileFormat/XmlFileLoggerLogFileFormatTests.cs
src/Cake.Issues.MsBuild.Tests/Testfiles/XmlFileLoggerLogFileFormat/IssueWithoutMessage.xml
src/Cake.Issues.MsBuild/LogFileFormat/BinaryLogFileFormat.cs
src/Cake.Issues.MsBuild/LogFileFormat/XmlFileLoggerLogFileFormat.cs

Ignore warnings without a message
Fixes #54

(GH-54) Ignore warnings without a message

---

src/Cake.Issues.MsBuild.Tests/Cake.Issues.MsBuild.Tests.csproj
src/Cake.Issues.MsBuild.Tests/LogFileFormat/XmlFileLoggerLogFileFormatTests.cs
src/Cake.Issues.MsBuild.Tests/Testfiles/XmlFileLoggerLogFileFormat/IssueWithAbsoluteFileNameAndWithoutTask.xml
src/Cake.Issues.MsBuild/LogFileFormat/XmlFileLoggerLogFileFormat.cs

Reproduces the issue reported in https://github.com/cake-contrib/Cake.Issues.MsBuild/issues/80
Fixes #80

(GH-80) MSBuild log generated by StyleCop throws ArgumentOutOfRangeException

---

src/Cake.Issues.MsBuild.Tests/Cake.Issues.MsBuild.Tests.csproj
src/Cake.Issues.MsBuild/Cake.Issues.MsBuild.csproj

Build against Cake 0.33.0
Fixes #88

(GH-88) Build against Cake 0.33.0

---

src/Cake.Issues.MsBuild.Tests/Cake.Issues.MsBuild.Tests.csproj
src/Cake.Issues.MsBuild.Tests/LogFileFormat/BinaryLogFileFormatTests.cs
src/Cake.Issues.MsBuild.Tests/LogFileFormat/XmlFileLoggerLogFileFormatTests.cs
src/Cake.Issues.MsBuild.Tests/MsBuildIssuesSettingsTests.cs
src/Cake.Issues.MsBuild/Cake.Issues.MsBuild.csproj

Update to Cake.Issues 0.7.0-beta001 
Fixes #89

 (GH-89) Update to Cake.Issues 0.7.0-beta001 

---

README.md
nuspec/nuget/Cake.Issues.MsBuild.nuspec

Change website to cakeissues.net
Fixes #110

(GH-110) Change website to cakeissues.net

---

src/Cake.Issues.MsBuild/MsBuildIssuesAliases.XmlFileLoggerLogFileFormat.cs

(GH-112) Fix namespace

---

src/Cake.Issues.MsBuild/MsBuildIssuesAliases.IssueProvider.cs
src/Cake.Issues.MsBuild/MsBuildIssuesProvider.cs

Make issue provider type name available on issue provider
Fixes #120

(GH-120) Make issue provider type name available on issue provider

---

src/Cake.Issues.MsBuild.Tests/Cake.Issues.MsBuild.Tests.csproj
src/Cake.Issues.MsBuild.Tests/FakeMsBuildLogFileFormat.cs
src/Cake.Issues.MsBuild/Cake.Issues.MsBuild.csproj
src/Cake.Issues.MsBuild/LogFileFormat/BinaryLogFileFormat.cs
src/Cake.Issues.MsBuild/LogFileFormat/XmlFileLoggerLogFileFormat.cs

Updates to Cake.Issues 0.8.0
Fixes #132

(GH-132) Update to Cake.Issues 0.8.0

---

docs/examples.md
docs/features.md

Update documentation for 0.8.0 release

Update documentation for 0.8.0

---

docs/features.md
src/Cake.Issues.MsBuild.Tests/Cake.Issues.MsBuild.Tests.csproj
src/Cake.Issues.MsBuild/Cake.Issues.MsBuild.csproj

Update to Cake.Issues 0.9.0
Fixes #167

(GH-167) Update to Cake.Issues 0.9.0

---

docs/features.md
src/Cake.Issues.MsBuild.Tests/LogFileFormat/XmlFileLoggerLogFileFormatTests.cs
src/Cake.Issues.MsBuild/LogFileFormat/XmlFileLoggerLogFileFormat.cs

Provide column in XmlFileLoggerFileFormat
Fixes #168

(GH-168) Provide column in XmlFileLoggerFileFormat

---

docs/features.md

Update documentation for Cake.Issues 0.9.0

Update documentation for Cake.Issues 0.9.0

---

src/Cake.Issues.MsBuild.Tests/Cake.Issues.MsBuild.Tests.csproj
src/Cake.Issues.MsBuild.Tests/FakeMsBuildLogFileFormat.cs
src/Cake.Issues.MsBuild/BaseMsBuildLogFileFormat.cs
src/Cake.Issues.MsBuild/Cake.Issues.MsBuild.csproj
src/Cake.Issues.MsBuild/LogFileFormat/BinaryLogFileFormat.cs
src/Cake.Issues.MsBuild/LogFileFormat/XmlFileLoggerLogFileFormat.cs

Update to Cake.Issues 0.9.0 Beta 2

Update to Cake.Issues 0.9.0 Beta 2

---

src/Cake.Issues.MsBuild.Tests/LogFileFormat/BinaryLogFileFormatTests.cs
src/Cake.Issues.MsBuild/LogFileFormat/BinaryLogFileFormat.cs

Provide column and range in BinaryLogFileFormat
Fixes #169 
Fixes #170

(GH-169)  Provide column and range in BinaryLogFileFormat

---

docs/features.md

Update documentation for reading errors
Part of #201

(GH-201) Update documentation for reading errors

---

src/Cake.Issues.MsBuild/LogFileFormat/BinaryLogFileFormat.cs

Support parsing of errors in BinaryLogFileFormat
Part of #201

(GH-201) Support parsing of errors in BinaryLogFileFormat 

---

src/Cake.Issues.MsBuild/LogFileFormat/BinaryLogFileFormat.cs
src/Cake.Issues.MsBuild/LogFileFormat/XmlFileLoggerLogFileFormat.cs

Fix naming of arguments and comments

Fix naming of arguments and comments

---

src/Cake.Issues.MsBuild/LogFileFormat/BinaryLogFileFormat.cs

Add missing XML comments

---

src/Cake.Issues.MsBuild/LogFileFormat/BinaryLogFileFormat.cs

Use correct issue priority for errors in binary logs

Use correct issue priority for errors in bin logs

---

src/Cake.Issues.MsBuild/LogFileFormat/BinaryLogFileFormat.cs
src/Cake.Issues.MsBuild/LogFileFormat/XmlFileLoggerLogFileFormat.cs

Improve logging while parsing log files
Fixes #200

(GH-200) Improve logging while parsing log files

---

src/Cake.Issues.MsBuild.Tests/Cake.Issues.MsBuild.Tests.csproj
src/Cake.Issues.MsBuild/Cake.Issues.MsBuild.csproj

Build against Cake.Issues 1.0
Fixes #230

(GH-230) Build against Cake.Issues 1.0

---

README.md

Removes duplicated build status from README

Remove duplicated build status from README

---

src/Cake.Issues.MsBuild.Tests/Cake.Issues.MsBuild.Tests.csproj
src/Cake.Issues.MsBuild.Tests/LogFileFormat/XmlFileLoggerLogFileFormatTests.cs
src/Cake.Issues.MsBuild/Cake.Issues.MsBuild.csproj

Update Cake.Issues to 2.0 Beta 1
Fixes #261

(GH-261) Update to Cake.Issues 2.0 Beta 1

---

recipe.cake

Disable coveralls since it is currently failing

Disable coveralls

---

src/Cake.Issues.MsBuild.Tests/Cake.Issues.MsBuild.Tests.csproj
src/Cake.Issues.MsBuild/Cake.Issues.MsBuild.csproj

Builds against Cake 3.0 and Cake.Issues 3.0 Beta 1
Fixes #287 
Fixes #288

Update for Cake 3.0 and Cake.Issues 3.0

---

src/.editorconfig
src/Cake.Issues.MsBuild.Tests/BaseMsBuildLogFileFormatTests.cs
src/Cake.Issues.MsBuild.Tests/LogFileFormat/BinaryLogFileFormatTests.cs
src/Cake.Issues.MsBuild.Tests/LogFileFormat/XmlFileLoggerLogFileFormatTests.cs
src/Cake.Issues.MsBuild.Tests/MsBuildIssuesProviderTests.cs
src/Cake.Issues.MsBuild.Tests/MsBuildIssuesSettingsTests.cs
src/Cake.Issues.MsBuild/LogFileFormat/BinaryLogFileFormat.cs
src/Cake.Issues.MsBuild/LogFileFormat/XmlFileLoggerLogFileFormat.cs
src/Cake.Issues.MsBuild/MsBuildRuleUrlResolver.cs

Adds an editorconfig file and fixes linting issues

Fix linting issues

---

src/Cake.Issues.MsBuild.Tests/MsBuildRuleUrlResolverTests.cs
src/Cake.Issues.MsBuild/MsBuildRuleUrlResolver.cs

Adds a rule to resolve links for SonarLint rules
Fixes #293

Add rule for resolving SonarLint rules

---

src/Cake.Issues.MsBuild/LogFileFormat/BinaryLogFileFormat.cs
src/Cake.Issues.MsBuild/LogFileFormat/XmlFileLoggerLogFileFormat.cs

Removes dupFinder exclusions, since we're no longer dupFinder as part of the build

Remove dupFinder exclusions

---

src/Cake.Issues.MsBuild.Tests/MsBuildRuleUrlResolverTests.cs
src/Cake.Issues.MsBuild/MsBuildRuleUrlResolver.cs

Adds rule for resolving Roslynator rules.
Fixes #295

(GH-295) Add rule for resolving Roslynator rules

---

.github/dependabot.yml

Disable Cake& Cake.Issues updates for all minor & patch updates

Disable Cake& Cake.Issues updates for all minor & patch updates

---

.github/renovate.json

Use Renovate config which is optimized for Cake.Issues addins

Use Cake.Issues specific Renovate config

---

docs/examples.md
docs/features.md

Fixes link to MSBuild Extension Pack
Fixes #342

(GH-342) Fix link to MSBuild Extension Pack

---

.appveyor.yml
azure-pipelines.yml
global.json
nuspec/nuget/Cake.Issues.MsBuild.nuspec
src/Cake.Issues.MsBuild.Tests/Cake.Issues.MsBuild.Tests.csproj
src/Cake.Issues.MsBuild.Tests/FakeMsBuildLogFileFormat.cs
src/Cake.Issues.MsBuild/Cake.Issues.MsBuild.csproj
src/Cake.Issues.MsBuild/LogFileFormat/XmlFileLoggerLogFileFormat.cs
src/Cake.Issues.MsBuild/MsBuildIssuesProvider.cs
src/Cake.Issues.MsBuild/MsBuildRuleUrlResolver.cs
src/Directory.Build.props

Multi-Target .NET 8 additionally
Fixes #357

Multi-Target .NET 8

---

src/Cake.Issues.MsBuild.Tests/Cake.Issues.MsBuild.Tests.csproj
src/Cake.Issues.MsBuild/Cake.Issues.MsBuild.csproj

Updates to Cake.Issues 4.0 Beta 1

Update to Cake.Issues 4.0 Beta 1

---

src/Cake.Issues.MsBuild/LogFileFormat/BinaryLogFileFormat.cs

Use primary constructor
